#!/bin/sh

S2E=/home/xqx/xqx/git/s2eforucore/build/qemu-release/i386-s2e-softmmu/qemu-system-i386

#$S2E  -rtc clock=vm -net user -net nic,model=ne2k_pci -parallel stdio -monitor telnet:localhost:4444,server,nowait \
#-hda /home/xqx/xqx/git/s2eforucore/lab5_result/bin/ucore.img -drive file=/home/xqx/xqx/git/s2eforucore/lab5_result/bin/swap.img,media=disk,cache=writeback -s -m 128 -s2e-config-file  ucoreconfig.lua

$S2E -hda /home/xqx/xqx/git/s2eforucore/lab5_result/bin/ucore.img -drive file=/home/xqx/xqx/git/s2eforucore/lab5_result/bin/swap.img,media=disk,cache=writeback -serial null -s2e-config-file $1 -s2e-verbose -d  in_asm,op,llvm_ir,out_asm

#$S2E -hda /home/xqx/s2eucore/ucore-s2e/lab5_result/bin/ucore.img -drive file=/home/xqx/s2eucore/ucore-s2e/lab5_result/bin/swap.img,media=disk,cache=writeback -serial null -s2e-config-file ucoreconfig.lua -s2e-verbose
