#!/bin/sh

S2E=/home/xqx/s2e/build/qemu-debug/i386-s2e-softmmu/qemu-system-i386


$S2E -hda /home/xqx/ucore/lab5/bin/ucore.img -drive file=/home/xqx/ucore/lab5/bin/swap.img,media=disk,cache=writeback -serial null -s2e-config-file config_ModuleTracer.lua -s2e-verbose 



